name: 'Run Tests in Wine'
description: 'Run Rust tests in Wine environment'

inputs:
  rust_project_path:
    description: 'Path to the Rust project'
    required: false
    default: '.'
  install_rust:
    description: 'Flag indicating if Rust should be installed'
    required: false
    default: 'true'
  rust_branch:
    description: 'Rust branch to use (nightly, stable, beta)'
    required: true
    default: 'stable'

runs:
  using: "composite"
  steps:
    - name: Install Stable Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'stable' }}
      uses: dtolnay/rust-toolchain@stable

    - name: Install Beta Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'beta' }}
      uses: dtolnay/rust-toolchain@beta

    - name: Install Nightly Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'nightly' }}
      uses: dtolnay/rust-toolchain@nightly

    # Cache Dependencies for Build Speed
    - name: Set environment variable
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Install Cross Compiler
      shell: bash
      run: |
        cargo +${{ inputs.rust_branch }} install cross --git https://github.com/cross-rs/cross

    - name: Run (Wine x86)
      shell: bash
      working-directory: ${{ inputs.rust_project_path }}
      run: |
        echo "Adding Windows (x86) Target"
        rustup target add i686-pc-windows-gnu

        echo "Building for Windows (x86)"
        cross +${{ inputs.rust_branch }} build --target i686-pc-windows-gnu

        echo "Testing Windows (x86)"
        cross +${{ inputs.rust_branch }} test --target i686-pc-windows-gnu

    - name: Run (Wine x64)
      shell: bash
      working-directory: ${{ inputs.rust_project_path }}
      run: |
        echo "Adding Windows (x64) Target"
        rustup target add x86_64-pc-windows-gnu

        echo "Building for Windows (x64)"
        cross +${{ inputs.rust_branch }} build --target x86_64-pc-windows-gnu

        echo "Testing Windows (x64)"
        cross +${{ inputs.rust_branch }} test --target x86_64-pc-windows-gnu