name: MkDocs build and deploy (Deprecated)

inputs:
  MKDOCS_VERSION:
    type: string
    required: false
    default: "latest"
    description: "MkDocs version to use"
  REQUIREMENTS:
    type: string
    required: false
    default: "./docs/requirements.txt"
    description: "Path to the requirements.txt file"
  CONFIG_FILE:
    type: string
    required: false
    default: "mkdocs.yml"
    description: "Path to the mkdocs.yml file"

runs:
  using: "composite"
  steps:
    - name: Deprecation Notice
      shell: bash
      run: |
        echo "::warning::This action is deprecated. Please use the workflow from https://github.com/Reloaded-Project/devops-mkdocs directly in your repository."

    - name: Invoke Reloaded-Project/devops-mkdocs Workflow
      uses: Reloaded-Project/devops-mkdocs@v1
      with:
        mkdocs-version: ${{ inputs.MKDOCS_VERSION }}
        requirements: ${{ inputs.REQUIREMENTS }}
        config-file: ${{ inputs.CONFIG_FILE }}