name: MkDocs build and deploy

inputs:
  MKDOCS_VERSION:
    type: string
    required: false
    default: "latest"
    description: "MkDocs version to use"
  REQUIREMENTS:
    type: string
    required: false
    default: "./docs/requirements.txt"
    description: "Path to the requirements.txt file"
  CONFIG_FILE:
    type: string
    required: false
    default: "mkdocs.yml"
    description: "Path to the mkdocs.yml file"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Build
      uses: Tiryoh/actions-mkdocs@v0.23.0
      with:
        mkdocs_version: ${{ inputs.MKDOCS_VERSION }}
        requirements: ${{ inputs.REQUIREMENTS }}
        configfile: ${{ inputs.CONFIG_FILE }}

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: "github-pages"
        path: "./site"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: "github-pages"