name: Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MkDocs
        uses: ./.github/actions/DeployMkDocs
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: ./docs/requirements.txt