name: Test and Upload Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-native:
    {% raw -%}
    runs-on: ${{ matrix.os }}
    {%- endraw %}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
{%- if xplat %}
          - macos-latest
          - windows-latest
{%- endif %}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: test-rust
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/test-and-coverage@v1 # upgrade if needed