[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
description = "{{project_description}}"
repository = "https://github.com/{{gh_username}}/{{project-name}}"
license-file = "LICENSE"
include = ["src/**/*"]

{% if std-by-default %}
[features]
default = ["std"]
std = []

{% if build-c-libs-with-pgo %}
# See README.md for more information.
pgo = []
{%- endif %}

{%- endif %}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
{%- if bench %}
criterion = "0.5.1"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.12", features = ["flamegraph", "criterion"] }{%- endif %}

# Profile Build
[profile.profile]
inherits = "release"
debug = true
codegen-units = 1
lto = true
strip = false  # No stripping!!

# Optimized Release Build
[profile.release]
codegen-units = 1
lto = true
strip = true  # Automatically strip symbols from the binary.
{%- if sizeopt %}
panic = "abort"
{%- endif %}

{%- if bench %}
# Benchmark Stuff
[[bench]]
name = "my_benchmark"
harness = false
{%- endif %}