name: 'Rust Run Test and Upload Coverage'
description: 'Runs cargo test and collects code coverage, uploading it to Codecov'

inputs:
  rust_project_path:
    description: 'Path to the Rust project'
    required: false
    default: '.'
  install_rust:
    description: 'Flag indicating if Rust should be installed'
    required: false
    default: 'true'
  upload_coverage:
    description: 'Flag indicating if coverage should be uploaded to codecov'
    required: false
    default: 'true'
  rust_branch:
    description: 'Rust branch to use (nightly, stable, beta)'
    required: true
    default: 'stable'

runs:
  using: 'composite'
  steps:
    - name: Install Stable Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'stable' }}
      uses: dtolnay/rust-toolchain@stable

    - name: Install Beta Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'beta' }}
      uses: dtolnay/rust-toolchain@beta

    - name: Install Nightly Rust
      if: ${{ inputs.install_rust == 'true' && inputs.rust_branch == 'nightly' }}
      uses: dtolnay/rust-toolchain@nightly

    # Cache Dependencies for Build Speed
    - name: Set environment variable
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Run Tarpaulin
      shell: bash
      working-directory: ${{ inputs.rust_project_path }}
      run: |
        cargo +${{ inputs.rust_branch }} install cargo-tarpaulin
        cargo +${{ inputs.rust_branch }} tarpaulin --all --release --out Xml --engine llvm

    - name: Upload Coverage to Codecov
      if: ${{ inputs.upload_coverage == 'true' }}
      uses: codecov/codecov-action@v3
      with:
        files: ${{ inputs.rust_project_path }}/cobertura.xml
        fail_ci_if_error: true
