name: 'Rust Run Test and Upload Coverage'
description: 'Runs cargo test and collects code coverage, uploading it to Codecov'

inputs:
  rust_project_path:
    description: 'Path to the Rust project'
    required: false
    default: '.'
  install_rust:
    description: 'Flag indicating if Rust should be installed'
    required: false
    default: 'true'
  upload_coverage:
    description: 'Flag indicating if coverage should be uploaded to codecov'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      if: ${{ inputs.install_rust == 'true' }}

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.1

    - name: Run Tarpaulin
      shell: bash
      working-directory: ${{ inputs.rust_project_path }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --all --release --out Xml --engine llvm

    - name: Upload Coverage to Codecov
      if: ${{ inputs.upload_coverage == 'true' }}
      uses: codecov/codecov-action@v2
      with:
        files: ${{ inputs.rust_project_path }}/cobertura.xml
        fail_ci_if_error: true
